CREATE TABLE users (
   id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   username varchar(15),
   password varchar(100)
) ;


CREATE TABLE roles (
   id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name varchar(15)
) ;

CREATE TABLE users_roles(
    user_id INT NOT NULL,
    roles_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (roles_id) REFERENCES roles(id),
    UNIQUE (user_id, roles_id)
);

INSERT INTO users VALUES
(1, 'zaur', 'zaur'),
(2, 'elena', 'elena'),
(3, 'ivan', 'ivan');

INSERT INTO roles VALUES
(1, 'ROLE_USER'),
(2, 'ROLE_ADMIN');

INSERT INTO users_roles VALUES
(1,1),
(2,2),
(3,1);